### ISSUE TITLE
Reestruturação do front-end

### ISSUE THREAD

**Issue by jpmota2208** [fga-eps-mds/2020.1-Conecta-Ensina-Wiki#104]
## Descrição

Na descrição da issue, você deve especificar melhor como o problema pode ser resolvido ou quais problemas são encontrados e por que o problema foi criado.

## Tarefas

- [x] Refatorar funções para a context
- [x] Refatorar componentes para melhorar modularização
- [x] Cartão do ZenHub atualizado
- [x] Registrar horas gastas no drive

**Comment by Denniel-sudo** [comment]
https://github.com/fga-eps-mds/2020.1-Conecta-Ensina-Mobile/pull/34
