### ISSUE TITLE
Criptografar senhas

### ISSUE THREAD

**Issue by jpmota2208** [fga-eps-mds/2020.1-Conecta-Ensina-Wiki#51]
## Descrição

A criptografia das senhas é algo essencial se pensamos na segurança dos nossos usuários, portanto é importante que todas as senhas estejam criptografadas no nosso banco de dados.

## Tarefas
- [x] Criar/ utilizar algoritmo de criptografia de senhas
- [x] Salvar senha criptografada no banco
- [x] Conseguir logar com a senha.

**Comment by Poulvilho** [comment]
const bcrypt = require('bcryptjs');

login = const passwordCorrect = await bcrypt.compare(password, user.password);
