### ISSUE TITLE
Separar variáveis do ambiente

### ISSUE THREAD

**Issue by jpmota2208** [fga-eps-mds/2020.1-Conecta-Ensina-Wiki#52]
## Descrição
As variáveis do ambiente facilitam a elaboração do front-end, otimizando o tempo do desenvolvedor e aproveitando código utilizado anteriormente.

## Tarefas

- [ ] Separar variáveis do ambiente
- [ ] Utilizar variáveis do ambiente no front

**Comment by Poulvilho** [comment]
const dotenv = require('dotenv').config();
