### ISSUE TITLE
Incorporar api do maps

### ISSUE THREAD

**Issue by jpmota2208** [fga-eps-mds/2020.1-Conecta-Ensina-Wiki#83]
## Descrição

Inserir a api do Google Maps para indicar a rota para o local de aula para o professor.

## Tarefas

- [x] Criar página que receberá o mapa
- [x] Adicionar o mapa
- [x] Separar as api keys em arquivos de ambiente
- [x] Testar
- [x] Cartão do ZenHub atualizado
- [x] Registrar horas gastas no drive

**Comment by jschneiderm98** [comment]
Em quais telas tem que colocar o mapa?

**Comment by jschneiderm98** [comment]
Sobre qual biblioteca usar para os mapas.

A primeira opção é  o [react-native-maps](https://github.com/react-native-maps/react-native-maps)

Como problemas pra essa opção se tem que é necessário ter uma api key do google, que requer registrar um meio de pagamento, além disso a instalação é mais problemática.

A segunda opção é o [react-native-mapbox-gl](https://github.com/react-native-mapbox-gl/maps)

Também que requer uma api key da mapbox, porém é muito mais simples de obter, e para poucos usos não é necessário registrar meio de pagamento.

A qualidade do mapa do google maps é sem dúvida melhor, porém as facilidade de se utilizar o mapbox me fazem a acreditar ser uma opção melhor. Dito isso qual seria a melhor opção?

**Comment by jpmota2208** [comment]
> Em quais telas tem que colocar o mapa?

A tela onde o mapa ficaria seria na tela de detalhes da aula, a mesma que possui o cronometro e as demais informações

**Comment by jschneiderm98** [comment]
Update sobre as bibliotecas. Acredito que teremos que usar a [react-native-maps](https://github.com/react-native-maps/react-native-maps), pois o recurso de geocoding(encontrar a latitude e longitude por meio de um endereço, ou no caso do google maps, por um CEP) do mapbox funciona muito mal para endereços no Brasil. Assim acredito ser melhor utilizar a [react-native-maps](https://github.com/react-native-maps/react-native-maps), pois é possível inclusive pesquisar localização por meio do CEP. Já consegui implementar a biblioteca no projeto, e funcionou bem o geocoding por CEP.
