### ISSUE TITLE
Inserir cronometro funcional

### ISSUE THREAD

**Issue by jpmota2208** [fga-eps-mds/2020.1-Conecta-Ensina-Wiki#85]
## Descrição

Na descrição da issue, você deve especificar melhor como o problema pode ser resolvido ou quais problemas são encontrados e por que o problema foi criado.

Histórias relacionadas:
- US20 - Eu, como professor, desejo ver a duração restante da aula, enquanto estou com o aluno.

## Tarefas

- [x] Inserir um cronômetro funcional na tela da aula
- [x] Cartão do ZenHub atualizado
- [x] Registrar horas gastas no drive

**Comment by Denniel-sudo** [comment]
quando um professor aceita uma aula para qual status ela passa? e para qual status vai após o professor dar a aula?

**Comment by Poulvilho** [comment]
@Denniel-sudo vide:
![image](https://user-images.githubusercontent.com/23237939/99316075-7755db00-2842-11eb-8d0f-26bc9e469905.png)

Quando aceita iria para o status 1. Pra onde vai após dar a aula teria de conferir com quem implementou a issue #86 para ver se foram pelo que estava pre setado no banco ou se fizeram alguma alteração.

**Comment by Denniel-sudo** [comment]
por algum motivo quando tento associar a issue ao pr n está aparecendo ela

**Comment by Denniel-sudo** [comment]
> @Denniel-sudo vide:
> ![image](https://user-images.githubusercontent.com/23237939/99316075-7755db00-2842-11eb-8d0f-26bc9e469905.png)
> 
> Quando aceita iria para o status 1. Pra onde vai após dar a aula teria de conferir com quem implementou a issue #86 para ver se foram pelo que estava pre setado no banco ou se fizeram alguma alteração.

e obrigado por tirar a dúvida

**Comment by Denniel-sudo** [comment]
o PR da issue foi realizado
