### ISSUE TITLE
Finalizar a aula (aluno e professor)

### ISSUE THREAD

**Issue by jpmota2208** [fga-eps-mds/2020.1-Conecta-Ensina-Wiki#86]
## Descrição

Com a aula em andamento, deve ser possível finalizar a aula.

## Tarefas

- [x] Inserir um botão na tela de aluno e professor, na tela da aula, para finalizar a aula.
- [x] Depois que ambos clicarem no botão, o status da aula deve passar de em andamento para finalizada.
- [x] Testar as rotas criadas.
- [x] Cartão do ZenHub atualizado
- [x] Registrar horas gastas no drive

**Comment by JoaoVitorFarias** [comment]
Pode usar apenas o cronômetro como parâmetro para definir se a aula já acabou ou é necessário um botão para confirmar? E caso o aluno ou professor queira terminar a aula antes do tempo, não seria melhor ele reporta para o administrador explicando o motivo ao invés de apenas apertar um botão?

**Comment by matgomes21** [comment]
Caso o finalizar aula seja um botão: de acordo com o banco, não tem o status de "finalização pendente" pra aula, então se qualquer um dos dois usuários (aluno ou professor) apertarem o botão de finalizar aula ela já acaba, ou deixa esse botão apenas para o professor?

**Comment by jpmota2208** [comment]
![image](https://user-images.githubusercontent.com/31632523/99477832-15749e80-2932-11eb-99c8-e84d41332348.png)
