### ISSUE TITLE
Avaliar professor

### ISSUE THREAD

**Issue by jpmota2208** [fga-eps-mds/2020.1-Conecta-Ensina-Wiki#87]
## Descrição

O aluno deve conseguir avaliar um professor após ter recebido sua aula.

Histórias relacionadas do backlog do produto:
- US21 - Eu, como aluno, desejo poder avaliar um professor após a finalização da aula.

## Tarefas

- [x] Na tela do aluno, após a aula ser finalizada, ter um botão para avaliar o professor.
- [x] Ir para um página separada com um campo de texto para o aluno dar até 5 estrelas e fazer o comentário que quiser.
- [x] Criar uma tabela no banco de dados para receber essa avaliação, com suas rotas e controllers.
- [ ] Testar
- [x] Registrar a avaliação no backend.
- [x] Cartão do ZenHub atualizado.
- [x] Registrar horas gastas no drive.

**Comment by matgomes21** [comment]
Na página que mostra a avaliação do professor para o aluno, essa avaliação é a própria avaliação que o aluno deu para esse professor anteriormente, ou é uma média de todas as avaliações que esse professor já recebeu (de diversos alunos)?
