### ISSUE TITLE
Avaliar aluno

### ISSUE THREAD

**Issue by jpmota2208** [fga-eps-mds/2020.1-Conecta-Ensina-Wiki#88]
## Descrição

O professor deve conseguir avaliar um aluno após ter lhe dado uma aula.

Histórias relacionadas do backlog do produto:
- US22 - Eu, como professor, desejo poder avaliar um aluno após ter lhe dado a aula.

## Tarefas

- [x] Na tela do professor, após a aula ser finalizada, ter um botão para avaliar o aluno.
- [x] Ir para um página separada com um campo de texto para o professor fazer o comentário que quiser. Nesta avaliação, não há estrelas para colocar.
- [x] Criar uma tabela no banco de dados para receber essa avaliação, com suas rotas e controllers.
- [x] Testar
- [x] Registrar a avaliação no backend.
- [x] Cartão do ZenHub atualizado
- [x] Registrar horas gastas no drive

**Comment by jschneiderm98** [comment]
Na nossa issue é pra professor avaliar o aluno?

**Comment by jpmota2208** [comment]
Sim, nesta issue, o professor vai avaliar o aluno.

**Comment by jschneiderm98** [comment]
Atualmente só tem uma rota no back que retorna todas as aulas, mas pra professor, as aulas são discriminadas em realizadas, confirmadas e pendentes. É criar uma nova rota, que pode puxar elas discriminadas pelo status?

**Comment by jpmota2208** [comment]
Sim. Faça isso, por favor.

**Comment by jschneiderm98** [comment]
Como que gera o ID pra fazer o teste de uma classe

**Comment by Poulvilho** [comment]
Roda o node no terminal
Importa a biblioteca que gera os IDs
Cria em uma variável no terminal
```
node
const { v4: uuidv4 } = require('uuid');
const id = uuidv4();
id;
```

**Comment by RhuanMr** [comment]
gente estamos planejando implementar a parte de denuncia na página de feedback, por isso j[a começamos a fazer a página, se puderem começar dando pull da nossa branch ficaríamos agradecidos

**Comment by Poulvilho** [comment]
@RhuanMr 

A parte de denúncias deve estar no perfil do outro usuário. Estamos partindo do princípio que não há a necessidade de ter uma aula pra poder denunciar. a denúncia pode ser feita em qualquer momento.

**Comment by jschneiderm98** [comment]
Seria interessante retornar as infos do estudante e do aluno quando acessar a rota da aula, ou só chama a rota de  estudante no back de novo?
