### ISSUE TITLE
Implementar denúncias

### ISSUE THREAD

**Issue by jpmota2208** [fga-eps-mds/2020.1-Conecta-Ensina-Wiki#89]
## Descrição

Um usuário deve ser capaz de reportar um outro usuário visualizando seu perfil.
Após a denúncia, este usuário muda seu status de ativo para reportado, limitando seu acesso na aplicação.

Histórias relacionadas:
- US24 - Eu, como professor ou estudante, desejo poder reportar outro professor ou estudante.

## Tarefas

- [x] Inserir botão de reportar quando estiver visualizando o perfil de outro usuário. Um usuário não pode se reportar.
- [x] Após clicar no botão, vai para uma nova página para que possa inserir um comentário no reporte.
- [x] Criar a tabela no backend, com sua model, controllers e rotas.
- [x] Registrar o reporte no backend, alterando o status do usuário.
- [x] Confirmar se esse usuário reportado aparece no relatório do administrador.
- [x] Testar
- [x] Cartão do ZenHub atualizado
- [x] Registrar horas gastas no drive

**Comment by Denniel-sudo** [comment]
Tem alguma tela em que o aluno consegue visualizar a aula que ele já esteve?

**Comment by Denniel-sudo** [comment]
@jpmota2208  @Poulvilho Qual o status de um usuário reportado?

**Comment by Poulvilho** [comment]
@Denniel-sudo Sei que existe a aba de aulas realizadas, mas não sei se a tela já foi criada. Quanto ao status, vide 
![image](https://user-images.githubusercontent.com/23237939/99618714-9ef2a200-2a00-11eb-9887-3035b84be5b3.png) há esse status -1 e 2 que talvez seja ambíguos visto que basta ser reportado uma vez pra já ter o acesso negado. Podem escolher um destes ou até criar um novo, apenas lembrando que se escolher um novo, mantenham esse comentário atualizado e documentem na issue.

**Comment by Denniel-sudo** [comment]
![image](https://user-images.githubusercontent.com/54074370/99916096-cab6a600-2ce6-11eb-959f-ab41e0f4dc65.png)
![image](https://user-images.githubusercontent.com/54074370/99916102-d73afe80-2ce6-11eb-92d3-c26dddfe777e.png)
![image](https://user-images.githubusercontent.com/54074370/99916106-e15cfd00-2ce6-11eb-9660-7bee6cf953e7.png)
![image](https://user-images.githubusercontent.com/54074370/99916123-ede15580-2ce6-11eb-98bd-1c621d3ac8da.png)

**Comment by Denniel-sudo** [comment]
https://github.com/fga-eps-mds/2020.1-Conecta-Ensina-Mobile/pull/30
https://github.com/fga-eps-mds/2020.1-Conecta-Ensina-Backend/pull/20

**Comment by jpmota2208** [comment]
![image](https://user-images.githubusercontent.com/31632523/100034513-15194f00-2ddb-11eb-837a-9cc8ee2257c4.png)

**Comment by jpmota2208** [comment]
Aprovado pelo cliente.
