### ISSUE TITLE
Implementar chat

### ISSUE THREAD

**Issue by jpmota2208** [fga-eps-mds/2020.1-Conecta-Ensina-Wiki#90]
## Descrição

A implementação do chat serve para estabelecer a comunicação entre o aluno e professor, sem depender de um aplicativo externo.

## Tarefas

- [x] Implementar o serviço de chat(API ou manual)
- [x] Após uma aula ser aceita, deve ser possível acessar o chat a partir dos detalhes da aula
- [x] Testar
- [x] Cartão do ZenHub atualizado
- [x] Registrar horas gastas no drive

**Comment by eddie-gomes** [comment]
O Chat faz parte da aula marcada (só fica disponível após a aula ser marcada e indisponível quando o status da aula muda para finalizada) ou é um recurso separado? Se sim, ela também pode fazer parte da tabela de Classroom?

**Comment by jpmota2208** [comment]
Sim, o chat só está disponível enquanto a aula está marcada e não foi realizada. Porém, não é possível guardar as informações do chat na tabela de Classroom.
